services:
  commandapi:
    build: 
      context: ../backend/Ticketing.CommandAPI
    container_name: commandapi
    ports:
      - "5000:5000"
    depends_on:
      - mssql
      - kafka-init
      - mongodb
      - redis
    restart: always
    environment:
      - ConnectionStrings__MSSQL=Server=ubuntu-sqlserver,1433;Database=TicketDB;User Id=sa;Password=@Ff04291001;TrustServerCertificate=True
      - Kafka__BootstrapServers=kafka:9092
    networks:
      - dockernet

  queryapi:
    build: 
      context: ../backend/Ticketing.QueryAPI
    container_name: queryapi
    ports:
      - "5001:5001"
    restart: always
    depends_on:
      - mssql
      - kafka-init
      - mongodb
      - redis
    environment:
      - MongoDbSettings__ConnectionString=mongodb://mongodb:27017
      - Kafka__BootstrapServers=kafka:9092
    networks:
      - dockernet