services:
  frontend:
    build: 
      context: ../frontend  # 指向 frontend 資料夾
    container_name: nuxt-app
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    working_dir: /app  # 設定工作目錄為 /app
    networks:
      - dockernet  # 設定網路，若需要與其他服務溝通（例如 backend）

  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: ubuntu-sqlserver
    restart: always
    environment:
      SA_PASSWORD: "@Ff04291001"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - dockernet
  
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
    networks:
      - dockernet

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - dockernet

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - dockernet

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - dockernet

volumes:
  mssql_data:
  mongo_data:

networks:
  dockernet:
    external: true